
advertisments:
  # -- advertisement 
  - name: default
    addressPools:
      # -- address pool name
      - name: default
        # -- ip ranges
        ipRanges:
          - 192.168.1.35-192.168.1.44
