{{- range .Values.advertisments}}
  {{- range .addressPools }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .name }}
  namespace: metallb-system
spec:
  addresses:
    {{- range .ipRanges }}
    - {{ .  }}
    {{- end }}   
---
  {{- end }} 
{{- end }}
