{{- range .Values.advertisments}}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .name }}
  namespace: metallb-system
spec: 
  ipAddressPools:
  {{- range .addressPools }}
    - {{ .name }}
  {{- end }}
---
{{- end }}